project:
  type: website
  output-dir: _site
  

website:
  title: "Mide Kanseri"
  favicon: "assets/images/biyikli.png"
  google-analytics: "G-RT0X40FTN3"
  site-url: "https://midekanseri.org/"
  description: "Mide kanseri ve ilişkili hastalıklar hakkında kapsamlı bilgi platformu"
  # announcement: 
  #   content: "**Mide Kanseri** üzerine herşey"
  #   position: below-navbar
  #   type: primary
  navbar:
    search: true
    left:
      - text: "Ana Sayfa"
        href: index.qmd
      - text: "Hasta rehberi"
        href: statik/hastalar/rehber/index.qmd
      - text: "Belgeler"
        href: statik/belgeler/index.qmd
      - text: "Biz Kimiz"
        href: statik/about/index.qmd
      - text: "İletişim"
        href: statik/iletisim/index.qmd  # İletişim bağlantısı
    right:
      - text: "Hastalıklar"
        menu:
          - text: "Mide kanseri (Adenokanser)"
            href: statik/hastalar/adenoca/index.qmd
          - text: "GIST"
            href: statik/hastalar/gist/index.qmd
          - text: "Nöroendokrin Tümör"
            href: statik/hastalar/net/index.qmd
          - text: "Lenfoma"
            href: statik/hastalar/lenfoma/index.qmd
          - text: "Diğer Mide Tümörleri"
            href: statik/hastalar/diger/index.qmd
          - text: "Özofagus Kanseri"
            href: statik/diger/ozofagus/index.qmd
          - text: "Gastroözofageal Reflü"
            href: statik/diger/gerd/index.qmd
          - text: "Hiatal Herni"
            href: statik/diger/herni/index.qmd
          - text: "Pankreas Kanseri"
            href: statik/diger/pankreas/index.qmd
      - text: "Doktorlar İçin"
        menu:
          - text: "Güncel Kılavuzlar"
            href: statik/doktorlar/kilavuzlar/index.qmd
          - text: "Önemli Makaleler"
            href: statik/doktorlar/makaleler/index.qmd
      - text: "Blog"
        href: blog.qmd 
  page-footer: "Bu websayfası **Prof. Dr. Ali Güner** tarafından hazırlanmıştır. Sayfa içeriği sadece bilgilendirme amaçlıdır, tanı ve tedavi için mutlaka doktorunuza başvurunuz."
  #   center:
      
        

# Blog Ayarları
blog:
  title: "Mide Kanseri Blog Yazıları"
  description: "Güncel gelişmeler ve haberler"
  author: "Ali Güner" 
  date-format: "DD/MM/YYYY"

format:
  html:
    theme: 
      - cosmo  # İsteğe bağlı tema
    css: assets/css/styles.css  # CSS dosyası
    toc: false
    toc-location: right
    page-layout: article
    title-block-banner: true
    smooth-scroll: true
    lang: tr  # Sayfa dili

execute:
  freeze: auto
  

